version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vinyl
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d vinyl" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails db:prepare && bin/rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/rails
      - ./app/assets/builds:/app/assets/builds
      - /app/vendor/bundle # Evita conflito de gems
      - /app/bin
    working_dir: /rails
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: vinyl

  css:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # O segredo está no -o (output) apontando para main.css
    command: bundle exec tailwindcss -i /rails/app/assets/stylesheets/main.css -o /rails/app/assets/builds/application.css --watch
    stdin_open: true
    tty: true
    volumes:
      - .:/rails
      - ./app/assets/builds:/app/assets/builds
      - /app/vendor/bundle
      - /app/bin
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: vinyl


volumes:
  db_data:
